version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    container_name: ttt-postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ttt-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - node-network

  app:
    build: .
    container_name: ttt-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://username:password@ttt-postgresdb:5432/ttt-db
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - node-network

volumes:
  postgres-data:

networks:
  node-network:
    driver: bridge
